### ISSUE TITLE
Track outbound links

### ISSUE THREAD

**Issue by bkrodgers** [MonsantoCo/engineering-blog#42]
Stephanie Bahr has asked that we start tracking outbound links.  In particular, the links to Discover Monsanto, Careers, Facebook, Twitter, Github, etc on the contact page.  We don't need to track outbound links to third party sites in individual blog posts.  We just want to gather data on what other Monsanto related sites the blog is driving traffic to.

See here for details on how:
https://support.google.com/analytics/answer/1136920?hl=en

**Comment by slbahr** [comment]
@bkrodgers ...  Any update on this?

**Comment by bkrodgers** [comment]
Sorry, I haven't had a chance to look at it yet.  I'll try to find some time soon.

**Comment by chrisshafer** [comment]
Adding analytics to the contact page https://github.com/MonsantoCo/engineering-blog/pull/47
